package com.bountychamp.userservice.dynamodb;

import java.util.Set;
import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.Setter;

import static com.bountychamp.userservice.dynamodb.DDBConstants.USER_TABLE_NAME;

@Getter
@Setter
@DynamoDBTable(tableName = USER_TABLE_NAME)
public class UserItem {

    @DynamoDBHashKey(attributeName = "UserId")
    @DynamoDBAutoGeneratedKey
    private UUID userId;

    @DynamoDBAttribute(attributeName="Username")
    private String username;

    @DynamoDBAttribute(attributeName="Email")
    private String email;

    @DynamoDBAttribute(attributeName="Password")
    private String password;
}
